config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  get '/auth/auth0/callback', to: 'sessions#auth0_success_callback'
  post '/auth/developer/callback', to: 'sessions#auth0_success_callback'

  get '/auth/failure', to: 'sessions#auth0_failure_callback'
  delete '/sessions', to: 'sessions#destroy'

  # Events
  post 'events/:type', to: 'events#create', as: 'events'

  # Projections
  resource :feature_reviews, only: [:new, :show, :create] do
    get 'search'
  end

  resources :releases, only: [:index, :show]

  resources :repository_locations,
    controller: 'git_repository_locations',
    as: 'git_repository_locations',
    only: [:index, :create]

  resources :tokens, only: [:index, :create, :update, :destroy]

  resources :github_notifications, only: [:create]
end

app/models/forms/feature_review_form.rb
require 'git_repository_loader'

require 'active_model'

module Forms
  class FeatureReviewForm
    extend ActiveModel::Naming
    include ActiveModel::AttributeMethods
    include ActiveModel::Validations

    attr_reader :uat_url, :apps

    def to_key
      nil
    end

    def initialize(apps:, git_repository_loader: nil, uat_url:)
      @apps = apps
      @git_repository_loader = git_repository_loader
      @uat_url = uat_url
    end

    def valid?
      errors.add(:base, 'Please specify at least one application version') if apps.empty?
      apps.each do |repo_name, version|
        begin
          repo = git_repository_loader.load(repo_name.to_s)
          errors.add(repo_name, "version #{version} does not exist") unless repo.exists?(version)
        rescue GitRepositoryLoader::NotFound
          errors.add(repo_name, 'does not exist')
        end
      end
      errors.empty?
    end

    def url
      hash = {}
      hash[:apps] = apps
      hash[:uat_url] = uat_url if uat_url.present?
      "/feature_reviews?#{hash.to_query}"
    end

    def apps
      return {} unless @apps
      @apps.select { |_app_name, version| version.present? }
    end

    private

    attr_reader :git_repository_loader
  end
end

app/controllers/feature_reviews_controller.rb
class FeatureReviewsController < ApplicationController
  def new
    @app_names = GitRepositoryLocation.app_names
    @feature_review_form = feature_review_form
  end

  def create
    @feature_review_form = feature_review_form
    if @feature_review_form.valid?
      redirect_to @feature_review_form.url
    else
      @app_names = GitRepositoryLocation.app_names
      render :new
    end
  end

  def show
    @return_to = request.original_fullpath
    feature_review = Factories::FeatureReviewFactory.new.create_from_url_string(request.original_url)
    @feature_review_with_statuses = FeatureReviewWithStatuses.new(feature_review, at: time)
  end

  def search
    @links = []
    @applications = GitRepositoryLocation.app_names
    @version = params[:version]
    @application = params[:application]

    return unless @version && @application

    versions = VersionResolver.new(git_repository_for(@application)).related_versions(@version)
    repository = Repositories::FeatureReviewRepository.new
    @links = repository.feature_reviews_for(versions: versions).map(&:url)
    flash[:error] = 'No Feature Reviews found.' if @links.empty?
  end

  private

  def time
    params.fetch(:time, nil).try { |t| Time.zone.parse(t) }
  end

  def feature_review_form
    form_input = params.fetch(:forms_feature_review_form, {})
    Forms::FeatureReviewForm.new(
      apps: form_input[:apps],
      uat_url: form_input[:uat_url],
      git_repository_loader: git_repository_loader,
    )
  end

  def git_repository_for(app_name)
    git_repository_loader.load(app_name)
  end
end

app/helpers/feature_reviews_helper.rb
module FeatureReviewsHelper
  def panel(heading:, klass: nil, **options, &block)
    status_panel = options.key?(:status)
    status = options.delete(:status)
    classes = status_panel ? panel_class(status) : 'panel-info'

    haml_tag('.panel', class: [klass, classes]) do
      haml_tag('.panel-heading') do
        haml_tag('h2') do
          icon(icon_class(status)) if status_panel
          haml_concat heading
        end
      end
      block.call
    end
  end

  def icon(classes)
    return unless classes
    attributes = { class: classes, aria: { hidden: true } }
    haml_tag('span.glyphicon', '', attributes)
  end

  def table(headers: [], classes: nil, &block)
    haml_tag('table.table.table-striped', class: classes) do
      haml_tag('thead') do
        haml_tag('tr') do
          headers.each do |header|
            haml_tag('th', header)
          end
        end
      end
      haml_tag('tbody', &block)
    end
  end

  def panel_class(status)
    "panel-#{item_class(status)}"
  end

  def text_class(status)
    "text-#{item_class(status)}"
  end

  def icon_class(status)
    "icon-#{item_class(status)}"
  end

  def item_status_icon_class(status)
    "#{icon_class(status)} status #{text_class(status)}"
  end

  def item_class(status)
    case status
    when true, :success
      'success'
    when false, :failure
      'danger'
    else
      'warning'
    end
  end

  def to_link(url, options = {})
    link_to url, Addressable::URI.heuristic_parse(url).to_s, options
  end
end

app/views/feature_reviews/index.html.haml
%h1
  - if @presenter.locked?
    - icon('icon-lock', tooltip: 'Feature Review is locked (all tickets done)')
  Feature Review

.row
  .col-lg-6
    - panel(heading: 'Summary', status: @presenter.summary_status, klass: 'summary') do
      %ul.list-group
        %li.list-group-item
          %strong
            - icon(item_status_icon_class(@presenter.build_status))
            %span.title Test Results
        %li.list-group-item
          %strong
            - icon(item_status_icon_class(@presenter.deploy_status))
            %span.title UAT Environment
        %li.list-group-item
          %strong
            - icon(item_status_icon_class(@presenter.qa_status))
            %span.title QA Acceptance
        %li.list-group-item
          %strong
            - icon(item_status_icon_class(@presenter.uatest_status))
            %span.title User Acceptance Tests

  .col-lg-6
    - panel(heading: 'Apps Under Review', klass: 'app-info') do
      %ul.list-group
        - @apps.each do |name, version|
          %li.list-group-item.app
            %strong.name= name
            %span.version= short_sha(version)
        %li.list-group-item
          - if @presenter.uat_url
            Deployed to UAT
            %strong.uat-url= to_link(@presenter.uat_url, target: '_blank')
          - else
            No UAT specified

.row
  .col-lg-12
    - panel(heading: 'Associated Tickets', klass: 'tickets') do
      - if @presenter.tickets.empty?
        .panel-body No tickets found
      - else
        - table(headers: %w(Key Summary Status)) do
          - @presenter.tickets.each do |ticket|
            %tr.ticket
              %td= ticket.key
              %td= ticket.summary
              %td= ticket.status

.row
  .col-lg-6
    - panel(heading: 'UAT Environment', klass: 'deploys', status: @presenter.deploy_status) do
      - if @presenter.deploys.empty?
        .panel-body No deploys found
      - else
        - table(headers: %w(Correct App Version)) do
          - @presenter.deploys.each do |deploy|
            %tr.deploy
              %td
                - icon(item_status_icon_class(deploy.correct))
              %td= deploy.app_name
              %td= short_sha(deploy.version)

  .col-lg-6
    - panel(heading: 'Test Results', klass: 'builds', status: @presenter.build_status) do
      - if @presenter.builds.empty?
        .panel-body No builds found
      - else
        - table(headers: %w(Status App Source)) do
          - @presenter.builds.each do |app_name, build|
            %tr.build
              %td
                - icon(item_status_icon_class(build.success))
              %td= app_name
              %td= build.source

.row
  .col-lg-6
    - panel(heading: 'QA Acceptance', klass: 'qa-submission', status: @presenter.qa_status) do
      .panel-body
        - if @presenter.qa_submission
          %p
            %span.qa-email
              %strong= @presenter.qa_submission.email
            at
            %span.qa-time= @presenter.qa_submission.created_at
          = simple_format(@presenter.qa_submission.comment, class: 'qa-comment')
        - else
          Not reviewed by QA
      .panel-footer
        = form_tag(events_path(type: 'manual_test', return_to: @return_to), method: 'post') do
          - @apps.each do |app_name, version|
            = hidden_field_tag('apps[][name]', app_name)
            = hidden_field_tag('apps[][version]', version)
          %label.radio-inline.qa-accept
            = radio_button_tag 'status', 'success', false, required: true, disabled: @presenter.locked?
            Accept
          %label.radio-inline.qa-reject
            = radio_button_tag 'status', 'failed', false, required: true, disabled: @presenter.locked?
            Reject
          .form-group
            = label_tag('comment', 'Comment', class: 'control-label sr-only')
            = text_area_tag('comment', '', placeholder: 'Comment', class: 'form-control', required: true, disabled: @presenter.locked?, rows: 4)
          = submit_tag('Submit', class: 'btn btn-primary', disabled: @presenter.locked?)
  .col-lg-6
    - panel(heading: 'User Acceptance Tests', klass: 'uatest', status: @presenter.uatest_status) do
      .panel-body
        - if @presenter.uatest
          Ran test suite version
          %span.uat-version= @presenter.uatest.test_suite_version
        - else
          Could not find User Acceptance Tests that ran against expected UAT
          = "(#{@presenter.uat_url})" if @presenter.uat_url
          with the app versions that are under review.

app/views/feature_reviews/new.html.haml
- title 'Prepare feature for review'

= form_for(@feature_review_form, url: feature_reviews_path, html: { class: 'form-horizontal' }) do |f|
  %ul.list-group
    - @feature_review_form.errors.full_messages.each do |error|
      %li.list-group-item.list-group-item-danger= error

  .row
    .col-md-6
      %h3 Applications

  = f.fields_for :apps do |field|
    - @app_names.each do |app_name|
      .form-group.row{class: @feature_review_form.errors[app_name].any? ? 'has-error' : nil }
        = field.label app_name, app_name, class: 'col-md-2 control-label'
        .col-md-4
          = field.text_field app_name, value: @feature_review_form.apps[app_name], class: 'form-control'
          - @feature_review_form.errors[app_name].each do |error|
            %span.help-inline= error

  .row
    .col-md-6
      %h3 User Acceptance Testing
  .form-group.row
    = f.label(:uat_url, "UAT environment", class: 'col-md-2 control-label')
    .col-md-4
      = f.text_field(:uat_url, placeholder: "URL", class: 'form-control')
  .row
    .col-md-6
      = f.submit("Submit", class: "btn btn-primary pull-right")

app/views/feature_reviews/search.html.haml
- title 'Feature Review Search'

= form_tag(search_feature_reviews_path, method: "get", class: 'form-horizontal', id: 'search-form') do
  .form-group
    = label_tag("application", "Application", class: 'col-sm-2 control-label')
    .col-sm-10
      = select_tag("application", options_for_select(@applications, @application), class: 'form-control')
  .form-group
    = label_tag("version", "Version", class: 'col-sm-2 control-label')
    .col-sm-10
      = text_field_tag("version", @version, placeholder: "Commit SHA", class: 'form-control')
  .form-group
    .col-sm-offset-2.col-sm-4
      = submit_tag("Search", class: "btn btn-primary")

- if @links.present?
  %table.table.table-striped
    %tr
      %th Feature Review Link
    - @links.each do |link|
      %tr
        %td= link_to 'Link', link, class: 'feature_review_link'

app/views/feature_reviews/show.html.haml
- title "Feature Review"
- if @feature_review_with_statuses.time
  .lead.time= "Projecting events up to #{@feature_review_with_statuses.time}"

.row
  .col-lg-6
    - panel(heading: 'Summary', status: @feature_review_with_statuses.summary_status, klass: 'summary') do
      %ul.list-group
        %li.list-group-item
          %strong
            - icon(item_status_icon_class(@feature_review_with_statuses.build_status))
            %span.title Test Results
        %li.list-group-item
          %strong
            - icon(item_status_icon_class(@feature_review_with_statuses.deploy_status))
            %span.title UAT Environment
        %li.list-group-item
          %strong
            - icon(item_status_icon_class(@feature_review_with_statuses.qa_status))
            %span.title QA Acceptance
        %li.list-group-item
          %strong
            - icon(item_status_icon_class(@feature_review_with_statuses.uatest_status))
            %span.title User Acceptance Tests

  .col-lg-6
    - panel(heading: 'Apps Under Review', klass: 'app-info') do
      %ul.list-group
        - @feature_review_with_statuses.app_versions.each do |name, version|
          %li.list-group-item.app
            %strong.name= name
            %span.version.monospace= short_sha(version)
        %li.list-group-item
          - if @feature_review_with_statuses.uat_url
            Deployed to UAT
            %strong.uat-url= to_link(@feature_review_with_statuses.uat_url, target: '_blank')
          - else
            No UAT specified

.row
  .col-lg-12
    - panel(heading: 'Associated Tickets', klass: 'tickets') do
      - if @feature_review_with_statuses.tickets.empty?
        .panel-body No tickets found
      - else
        - table(headers: %w(Key Summary Status)) do
          - @feature_review_with_statuses.tickets.each do |ticket|
            %tr.ticket
              %td= ticket.key
              %td= ticket.summary
              %td= ticket.status

.row
  .col-lg-6
    - panel(heading: 'UAT Environment', klass: 'deploys', status: @feature_review_with_statuses.deploy_status) do
      - if @feature_review_with_statuses.deploys.empty?
        .panel-body No deploys found
      - else
        - table(headers: %w(Correct App Version)) do
          - @feature_review_with_statuses.deploys.each do |deploy|
            %tr.deploy
              %td
                - icon(item_status_icon_class(deploy.correct))
              %td= deploy.app_name
              %td.monospace= short_sha(deploy.version)

  .col-lg-6
    - panel(heading: 'Test Results', klass: 'builds', status: @feature_review_with_statuses.build_status) do
      - if @feature_review_with_statuses.builds.empty?
        .panel-body No builds found
      - else
        - table(headers: %w(Status App Source)) do
          - @feature_review_with_statuses.builds.each do |app_name, build|
            %tr.build
              %td
                - icon(item_status_icon_class(build.success))
              %td= app_name
              %td= build.source

.row
  .col-lg-6
    - panel(heading: 'QA Acceptance', klass: 'qa-submission', status: @feature_review_with_statuses.qa_status) do
      .panel-body
        - if @feature_review_with_statuses.qa_submission
          %p
            %span.qa-email
              %strong= @feature_review_with_statuses.qa_submission.email
            at
            %span.qa-time= @feature_review_with_statuses.qa_submission.created_at
          = simple_format(@feature_review_with_statuses.qa_submission.comment, class: 'qa-comment')
        - else
          Not reviewed by QA
      .panel-footer
        = form_tag(events_path(type: 'manual_test', return_to: @return_to), method: 'post') do
          - @feature_review_with_statuses.app_versions.each do |app_name, version|
            = hidden_field_tag('apps[][name]', app_name)
            = hidden_field_tag('apps[][version]', version)
          %label.radio-inline.qa-accept
            = radio_button_tag 'status', 'success', false, required: true
            Accept
          %label.radio-inline.qa-reject
            = radio_button_tag 'status', 'failed', false, required: true
            Reject
          .form-group
            = label_tag('comment', 'Comment', class: 'control-label sr-only')
            = text_area_tag('comment', '', placeholder: 'Comment', class: 'form-control', required: true, rows: 4)
          = submit_tag('Submit', class: 'btn btn-primary')
  .col-lg-6
    - panel(heading: 'User Acceptance Tests', klass: 'uatest', status: @feature_review_with_statuses.uatest_status) do
      .panel-body
        - if @feature_review_with_statuses.uatest
          Ran test suite version
          %span.uat-version= @feature_review_with_statuses.uatest.test_suite_version
        - else
          Could not find User Acceptance Tests that ran against expected UAT
          = "(#{@feature_review_with_statuses.uat_url})" if @feature_review_with_statuses.uat_url
          with the app versions that are under review.