config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  get '/auth/auth0/callback', to: 'sessions#auth0_success_callback'
  post '/auth/developer/callback', to: 'sessions#auth0_success_callback'

  get '/auth/failure', to: 'sessions#auth0_failure_callback'
  delete '/sessions', to: 'sessions#destroy'

  # Events
  post 'events/:type', to: 'events#create', as: 'events'

  # Projections
  resource :feature_reviews, only: [:new, :show, :create] do
    get 'search'
  end

  resources :releases, only: [:index, :show]

  resources :repository_locations,
    controller: 'git_repository_locations',
    as: 'git_repository_locations',
    only: [:index, :create]

  resources :tokens, only: [:index, :create, :update, :destroy]

  resources :github_notifications, only: [:create]
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ShipmentTracker
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body

    .navbar.navbar-default
      .container
        .navbar-header
          %a.navbar-brand{href: '/'}
            Shipment Tracker
        %ul.navbar-nav.nav
          %li
            = link_to 'Prepare review', new_feature_reviews_path
          %li
            = link_to 'Search reviews', search_feature_reviews_path
          %li
            = link_to 'Repository locations', git_repository_locations_path
          %li
            = link_to 'Releases', releases_path
          %li
            = link_to 'API Tokens', tokens_path
        %ul.nav.navbar-nav.navbar-right
          - if current_user.logged_in?
            %li
              %p.navbar-text
                %small= current_user.email
            %li
              = button_to 'Log out', { controller: 'sessions', action: 'destroy'}, method: :delete, class: 'btn btn-secondary navbar-btn'
          - else
            %li
              = link_to 'Log in', login_url
    .container
      - if flash[:error] # the red one
        .alert.alert-danger= flash[:error]
      - if flash[:warning] # the yellow one
        .alert.alert-warning= flash[:warning]
      - if flash[:success] # the green one
        .alert.alert-success= flash[:success]
      - if flash[:info] # the blue one
        .alert.alert-info= flash[:info]
      = yield